@host = http://localhost:8080/
@contentType = application/json

###
GET {{host}}completion
Content-Type: {{contentType}}

{
    "question": "Do que fala o arquivo de id file-3iAxjWsbxZay5c82c7jWI9lF?"
}

###
POST {{host}}file
Content-Type: {{contentType}}

###
POST {{host}}assistant
Content-Type: {{contentType}}
