@host = http://localhost:8080/
@contentType = application/json

###
POST {{host}}completion
Content-Type: {{contentType}}

{
    "json": "'titulo_artigo':, 'autores':[], 'universidade':, 'ano':, 'doencas':[ {'nome_doenca':,'sintomas':[],'tratamentos':[]}]",
    "model": "gpt-4-turbo-preview"
}
